[package]
name = "my-budget"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.38"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
lazy_static = "1.5.0"

[dependencies.rocket]
version = "0.5"
features = ["json"]
